# Generated by Django 3.1.3 on 2020-11-20 19:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_account_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='stripe_account_token'),
            preserve_default=False,
        ),
    ]
