# Generated by Django 3.1.3 on 2020-12-06 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201121_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_onboarding_link',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='stripe_onboarding_link'),
            preserve_default=False,
        ),
    ]
