# Generated by Django 3.1.3 on 2020-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_company_stripe_onboarding_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_long',
            field=models.FloatField(default=-122.83168810495914),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.FloatField(default=42.3514230271763),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='max_distance',
            field=models.FloatField(default=50.0),
            preserve_default=False,
        ),
    ]
