// Ad Actions
export const GET_ADS = "GET_ADS";
export const CLEAR_ADS = "CLEAR_ADS";
export const SAVE_AD = "SAVE_AD";
export const POST_AD = "POST_AD";
export const UPDATE_AD = "UPDATE_AD";
export const DELETE_AD = "DELETE_AD";
export const SET_LOADING = "SET_LOADING";
export const ADS_ERROR = "ADS_ERROR";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
// Facebook Interest Actions
export const SET_INTERESTS = "SET_INTERESTS";
export const GET_INTERESTS = "GET_INTERESTS";
export const SAVE_INTEREST = "SAVE_INTEREST";
export const DELETE_INTEREST = "DELETE_INTEREST";
export const CLEAR_INTERESTS = "CLEAR_INTERESTS";
export const UPDATE_INTEREST = "UPDATE_INTEREST";
export const SET_INTEREST_LOADING = "SET_INTEREST_LOADING";
// Facebook Location Actions
export const GET_LOCATIONS = "GET_LOCATIONS";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const CLEAR_LOCATIONS = "CLEAR_LOCATIONS";
export const SAVE_LOCATION = "SAVE_LOCATION";
export const UPDATE_LOCATION = "UPDATE_LOCATION";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const SET_LOCATION_LOADING = "SET_LOCATION_LOADING";
// Google Interest Actions
export const SET_GOOGLE_INTERESTS = "SET_GOOGLE_INTERESTS";
export const GET_GOOGLE_INTERESTS = "GET_GOOGLE_INTERESTS";
export const SAVE_GOOGLE_INTEREST = "SAVE_GOOGLE_INTEREST";
export const DELETE_GOOGLE_INTEREST = "DELETE_GOOGLE_INTEREST";
export const CLEAR_GOOGLE_INTERESTS = "CLEAR_GOOGLE_INTERESTS";
export const UPDATE_GOOGLE_INTEREST = "UPDATE_GOOGLE_INTEREST";
export const SET_GOOGLE_INTEREST_LOADING = "SET_GOOGLE_INTEREST_LOADING";
// Google Keyword Actions
export const SET_GOOGLE_KEYWORDS = "SET_GOOGLE_KEYWORDS";
export const ADD_KEYWORD_TO_PLAN = "ADD_KEYWORD_TO_PLAN";
export const DELETE_KEYWORD_FROM_PLAN = "DELETE_KEYWORD_FROM_PLAN";
export const GET_GOOGLE_KEYWORDS = "GET_GOOGLE_KEYWORDS";
export const SAVE_GOOGLE_KEYWORD = "SAVE_GOOGLE_KEYWORD";
export const DELETE_GOOGLE_KEYWORD = "DELETE_GOOGLE_KEYWORD";
export const CLEAR_GOOGLE_KEYWORDS = "CLEAR_GOOGLE_KEYWORDS";
export const UPDATE_GOOGLE_KEYWORD = "UPDATE_GOOGLE_KEYWORD";
export const SET_GOOGLE_KEYWORD_LOADING = "SET_GOOGLE_KEYWORD_LOADING";
// Google Location Actions
export const GET_GOOGLE_LOCATIONS = "GET_GOOGLE_LOCATIONS";
export const SET_GOOGLE_LOCATIONS = "SET_GOOGLE_LOCATIONS";
export const CLEAR_GOOGLE_LOCATIONS = "CLEAR_GOOGLE_LOCATIONS";
export const SAVE_GOOGLE_LOCATION = "SAVE_GOOGLE_LOCATION";
export const UPDATE_GOOGLE_LOCATION = "UPDATE_GOOGLE_LOCATION";
export const DELETE_GOOGLE_LOCATION = "DELETE_GOOGLE_LOCATION";
export const SET_GOOGLE_LOCATION_LOADING = "SET_GOOGLE_LOCATION_LOADING";
// Facebook Ad Accounts Actions
export const SET_FB_AD_ACCOUNTS = "SET_FB_AD_ACCOUNTS";
export const GET_FB_AD_ACCOUNTS = "GET_FB_AD_ACCOUNTS";
export const SAVE_FB_AD_ACCOUNT = "SAVE_FB_AD_ACCOUNT";
export const DELETE_FB_AD_ACCOUNT = "DELETE_FB_AD_ACCOUNT";
export const SET_FB_AD_ACCOUNT_LOADING = "SET_FB_AD_ACCOUNT_LOADING";
export const SAVE_FB_TOKEN = "SAVE_FB_TOKEN";
// Google Ad Accounts Actions
export const SET_GOOGLE_AD_ACCOUNTS = "SET_GOOGLE_AD_ACCOUNTS";
export const GET_GOOGLE_AD_ACCOUNTS = "GET_GOOGLE_AD_ACCOUNTS";
export const SAVE_GOOGLE_AD_ACCOUNT = "SAVE_GOOGLE_AD_ACCOUNT";
export const DELETE_GOOGLE_AD_ACCOUNT = "DELETE_GOOGLE_AD_ACCOUNT";
export const SET_GOOGLE_AD_ACCOUNT_LOADING = "SET_GOOGLE_AD_ACCOUNT_LOADING";
export const SAVE_GOOGLE_TOKEN = "SAVE_GOOGLE_TOKEN";

// Google Ad Accounts Actions
export const GET_SOCIAL_AUTHS = "GET_SOCIAL_AUTHS";

// Google Manager Accounts Actions
export const GET_GOOGLE_MANAGER_ACCOUNTS = "GET_GOOGLE_MANAGER_ACCOUNTS";
export const SAVE_GOOGLE_MANAGER_ACCOUNT = "SAVE_GOOGLE_MANAGER_ACCOUNT";
export const DELETE_GOOGLE_MANAGER_ACCOUNT = "DELETE_GOOGLE_MANAGER_ACCOUNT";
export const SET_GOOGLE_MANAGER_ACCOUNT_LOADING =
  "SET_GOOGLE_MANAGER_ACCOUNT_LOADING";
// Facebook Auth
export const FBPROFILE_LOADING = "USER_LOADING";
export const FBPROFILE_LOADED = "USER_LOADED";
export const FBAUTH_ERROR = "AUTH_ERROR";
export const FBLOGIN_SUCCESS = "LOGIN_SUCCESS";
export const FBLOGIN_FAIL = "LOGIN_FAIL";
export const FBLOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// End Facebook Auth Actions
// Google Auth
export const GSPROFILE_LOADING = "USER_LOADING";
export const GSPROFILE_LOADED = "USER_LOADED";
export const GSAUTH_ERROR = "AUTH_ERROR";
export const GSLOGIN_SUCCESS = "LOGIN_SUCCESS";
export const GSLOGIN_FAIL = "LOGIN_FAIL";
export const GSLOGOUT_SUCCESS = "LOGOUT_SUCCESS";
// End Google Auth Actions



export const UPDATE_SOCIALS = "UPDATE_SOCIALS";
export const UPDATE_TARGETS = "UPDATE_TARGETS";
export const UPDATE_BUDGET = "UPDATE_BUDGET";
// Basic Info Actions 
export const UPDATE_BASIC_INFO_NAME = "UPDATE_BASIC_INFO_NAME";
export const UPDATE_BASIC_INFO_BUSINESS = "UPDATE_BASIC_INFO_BUSINESS";
export const UPDATE_BASIC_INFO_WEBSITE = "UPDATE_BASIC_INFO_WEBSITE";
export const UPDATE_BASIC_INFO_STREET = "UPDATE_BASIC_INFO_STREET";
export const UPDATE_BASIC_INFO_CITY = "UPDATE_BASIC_INFO_CITY";
export const UPDATE_BASIC_INFO_STATE = "UPDATE_BASIC_INFO_STATE";
export const UPDATE_BASIC_INFO_ZIP = "UPDATE_BASIC_INFO_ZIP";
// Address Actions
export const SET_ADDRESSES = "SET_ADDRESSES";
export const GET_ADDRESSES = "GET_ADDRESSES";
export const SAVE_ADDRESS = "SAVE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const CLEAR_ADDRESSES = "CLEAR_ADDRESSES";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const SET_ADDRESS_LOADING = "SET_ADDRESS_LOADING";
// campaign actions
export const MAKE_CURRENT = "MAKE_CURRENT";
export const GET_CAMPAIGNS = "GET_CAMPAIGNS";
export const SAVE_CAMPAIGN = "SAVE_CAMPAIGN";
export const ADD_CAMPAIGN = "ADD_CAMPAIGN";
export const DELETE_CAMPAIGN = "DELETE_CAMPAIGN";
export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";
export const SET_CAMPAIGN_LOADING = "SET_CAMPAIGN_LOADING";
// Business Info
export const GET_BUSINESS_INFOS = "GET_BUSINESS_INFOS";
export const SAVE_BUSINESS_INFO = "SAVE_BUSINESS_INFO";
export const ADD_BUSINESS_INFO = "ADD_BUSINESS_INFO";
export const DELETE_BUSINESS_INFO = "DELETE_BUSINESS_INFO";
export const UPDATE_BUSINESS_INFO = "UPDATE_BUSINESS_INFO";
export const SET_BUSINESS_INFO_LOADING = "SET_BUSINESS_INFO_LOADING";

// Social Account Info Actions
export const UPDATE_FACEBOOK_ACCOUNT_INFO = "UPDATE_FACEBOOK_ACCOUNT_INFO";
export const UPDATE_GOOGLE_ACCOUNT_INFO = "UPDATE_GOOGLE_ACCOUNT_INFO";
