# Generated by Django 3.1.3 on 2020-11-08 22:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='payment_hash',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='payment-hash'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rental_start', models.DateTimeField(verbose_name='rental-start')),
                ('rental_end', models.DateTimeField(verbose_name='rental-end')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='rental', to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('rental_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.rentalitem')),
            ],
            options={
                'db_table': 'rentals',
                'ordering': ['rental_start'],
            },
        ),
    ]
