# Generated by Django 3.1.3 on 2020-11-26 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20201108_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='payment_hash',
        ),
        migrations.AddField(
            model_name='customer',
            name='stripe_customer_token',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='stripe-customer-token'),
            preserve_default=False,
        ),
    ]
