# Generated by Django 3.1.3 on 2020-12-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_customer_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='_long',
            field=models.FloatField(default=-119.32878750554688),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalitem',
            name='lat',
            field=models.FloatField(default=40.56602875373934),
            preserve_default=False,
        ),
    ]
