# Generated by Django 3.1.4 on 2020-12-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_customer_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalitem',
            name='image',
            field=models.ImageField(null=True, upload_to='./save_to', verbose_name='image'),
        ),
    ]
