# Generated by Django 3.1.3 on 2020-11-30 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0005_customer_payment_method'),
        ('accounts', '0003_auto_20201121_0947'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('stripe_payment_intent', models.CharField(max_length=250, verbose_name='stripe-payment-intent')),
                ('company', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='accounts.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.rental')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['date'],
            },
        ),
    ]
