# Generated by Django 3.1.3 on 2020-12-01 05:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='user_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='user-id'),
            preserve_default=False,
        ),
    ]
