# Generated by Django 3.1.3 on 2020-12-06 00:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20201201_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_confirmation',
            field=models.CharField(default=django.utils.timezone.now, max_length=250, verbose_name='stripe-payment-confirmation'),
            preserve_default=False,
        ),
    ]
